import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docsSidebar: [
    {
      type: 'doc',
      id: 'rewrite',
      label: '⚠️ Upcoming Changes'
    },
    {
      type: 'category',
      label: 'Getting Started',
      // Explicit list (rather than autogenerated) so the setup path stays a
      // focused funnel and the competition/reference pages can live in their
      // own top-level sections below. Files remain in `1-getting-started/`, so
      // page URLs are unchanged.
      items: [
        'getting-started/about',
        'getting-started/quick-start',
        'getting-started/adapters',
        'getting-started/device-setup',
        'getting-started/app-setup',
        'getting-started/mounting',
        'getting-started/wiring',
        'getting-started/simulation',
        'getting-started/robot-code',
      ],
    },
    {
      type: 'category',
      label: 'Competition Day',
      items: [
        'getting-started/calibration',
        'getting-started/pre-match-checklist',
        'getting-started/post-match-checklist',
      ],
    },
    {
      type: 'doc',
      id: 'getting-started/webcam',
    },
    {
      type: 'doc',
      id: 'getting-started/troubleshooting',
    },
    {
      type: 'category',
      label: 'Development & Contributing',
      items: [
        {
          type: 'autogenerated',
          dirName: '2-development',
        },
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        {
          type: 'doc',
          id: 'api-reference/index',
          label: 'Overview',
        },
        {
          type: 'doc',
          id: 'api-reference/web-api',
          label: 'Web API',
        },
        {
          type: 'link',
          label: 'Protocol Buffers →',
          href: 'https://questnav.gg/static/api/proto/',
        },
        {
          type: 'link',
          label: 'Java API →',
          href: 'https://questnav.gg/static/api/java/',
        },
        {
          type: 'link',
          label: 'C# API →',
          href: 'https://questnav.gg/static/api/csharp/',
        },
      ],
    },
  ],
};

export default sidebars;
