name: Build QuestNavLib

on:
  workflow_call:
    inputs:
      versionYear:
        description: 'Current FRC Year'
        required: true
        default: 2025
        type: number
      versionMajor:
        description: 'Major version'
        required: true
        default: 1
        type: number
      versionMinor:
        description: 'Minor version'
        required: true
        default: 0
        type: number
      versionPatch:
        description: 'Patch version'
        required: true
        default: 0
        type: number
      wpilibVersion:
        description: 'WPILib version to compile for'
        required: true
        type: string
        default: '2025.3.2'
      versionType:
        description: 'Type of version'
        required: false
        type: string

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2

jobs:
  build-questnavlib:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: questnav-lib
    outputs:
      jar-artifact-name: ${{ steps.upload.outputs.artifact-id }}
      jar-filename: ${{ steps.buildJava.outputs.buildVersion }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: questnav-lib
          sparse-checkout-cone-mode: false

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.11'

      - name: Make gradlew Executable
        run: 'chmod +x ./gradlew'

      - name: Display Build Configuration
        run: |
          ./gradlew buildInfo \
            -PquestnavVersion="${{ inputs.versionMajor }}.${{ inputs.versionMinor }}.${{ inputs.versionPatch }}" \
            -PreleaseType="${{ inputs.versionType }}" \
            -PfrcYear="${{ inputs.versionYear }}" \
            -PwpilibVersion="${{ inputs.wpilibVersion }}"

      - name: Cache Gradle Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-lib-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-lib-

      - name: Build Library
        run: |
          ./gradlew build \
            -PquestnavVersion="${{ inputs.versionMajor }}.${{ inputs.versionMinor }}.${{ inputs.versionPatch }}" \
            -PreleaseType="${{ inputs.versionType }}" \
            -PfrcYear="${{ inputs.versionYear }}" \
            -PwpilibVersion="${{ inputs.wpilibVersion }}"

      - name: Generate Vendor JSON
        run: |
          ./gradlew generateVendorJson \
            -PquestnavVersion="${{ inputs.versionMajor }}.${{ inputs.versionMinor }}.${{ inputs.versionPatch }}" \
            -PreleaseType="${{ inputs.versionType }}" \
            -PfrcYear="${{ inputs.versionYear }}" \
            -PwpilibVersion="${{ inputs.wpilibVersion }}"

      - name: Prepare Artifacts
        run: |
          ./gradlew copyVendorJsonLocal \
            -PquestnavVersion="${{ inputs.versionMajor }}.${{ inputs.versionMinor }}.${{ inputs.versionPatch }}" \
            -PreleaseType="${{ inputs.versionType }}" \
            -PfrcYear="${{ inputs.versionYear }}" \
            -PwpilibVersion="${{ inputs.wpilibVersion }}"
          
          # Create artifacts directory
          mkdir -p artifacts
          
          # Copy vendor JSON with versioned filename
          cp build/generated/vendordeps/questnavlib.json artifacts/questnavlib-${{ inputs.versionYear }}-${{ inputs.versionMajor }}.${{ inputs.versionMinor }}.${{ inputs.versionPatch }}${{ inputs.versionType && format('-{0}', inputs.versionType) || '' }}.json
          cp build/generated/vendordeps/questnavlib.json artifacts/questnavlib.json

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.versionYear }}-${{ inputs.versionMajor }}.${{ inputs.versionMinor }}.${{ inputs.versionPatch }}${{ inputs.versionType && format('-{0}', inputs.versionType) || '' }}
          path: artifacts/
          retention-days: 7

