name: CSharp Formatting Check

on:
  pull_request:
    paths:
      - '**.cs'

jobs:
  format-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install CSharpier
        run: dotnet tool install -g csharpier

      - name: Check CSharp formatting
        run: csharpier check unity/Assets/QuestNav/