name: Compile Protocol Buffers
on:
  push:
    paths:
      - 'protos/*'
      - 'questnav-lib/src/main/java/gg/questnav/questnav/protos/generated/*'
      - 'unity/Assets/QuestNav/Protos/Generated/*'
  pull_request_target:
    branches:
      - main
    paths:
      - 'protos/*'
      - 'questnav-lib/src/main/java/gg/questnav/questnav/protos/generated/*'
      - 'unity/Assets/QuestNav/Protos/Generated/*'
  workflow_dispatch:
  workflow_call:
jobs:
  compile-protobufs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Install protoc
        uses: arduino/setup-protoc@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download QuickBuf plugin
        id: download-quickbuf
        uses: clausnz/github-action-download-maven-artifact@master
        with:
          url: 'https://repo1.maven.org'
          repository: 'maven2'
          groupId: 'us.hebi.quickbuf'
          artifactId: 'protoc-gen-quickbuf'
          version: '1.4'
          extension: 'exe'
          classifier: 'linux-x86_64'

      - name: Setup QuickBuf
        run: chmod +x ${{ steps.download-quickbuf.outputs.file }}

      - name: Generate C# protobuf
        run: protoc -I="protos" --csharp_out=unity/Assets/QuestNav/Protos/Generated protos/*.proto

      - name: Generate Java QuickBuffers
        run: |
          protoc \
            -I="protos" \
            --plugin=protoc-gen-quickbuf=${{ steps.download-quickbuf.outputs.file }} \
            --quickbuf_out=gen_descriptors=true,indent=4:questnav-lib/src/main/java/ \
            protos/*.proto

      - name: Commit all generated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'ci: Generated Protocol Buffers'
          file_pattern: 'unity/Assets/QuestNav/Protos/Generated/*.cs questnav-lib/src/main/java/gg/questnav/questnav/protos/generated/*.java'