name: Compile Protocol Buffers
on:
  push:
    paths:
      - 'protos/*'
      - 'questnav-lib/src/main/java/gg/questnav/questnav/protos/generated/*'
      - 'unity/Assets/QuestNav/Protos/Generated/*'
      - 'questnav-lib/src/main/native/cpp/gg/questnav/questnav/protos/generated/*'
      - 'questnav-lib/src/main/native/include/gg/questnav/questnav/protos/generated/*'
  pull_request_target:
    branches:
      - main
    paths:
      - 'protos/*'
      - 'questnav-lib/src/main/java/gg/questnav/questnav/protos/generated/*'
      - 'unity/Assets/QuestNav/Protos/Generated/*'
  workflow_dispatch:
jobs:
  compile-protobufs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Install protoc
        uses: arduino/setup-protoc@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download QuickBuf plugin
        id: download-quickbuf
        uses: clausnz/github-action-download-maven-artifact@master
        with:
          url: 'https://repo1.maven.org'
          repository: 'maven2'
          groupId: 'us.hebi.quickbuf'
          artifactId: 'protoc-gen-quickbuf'
          version: '1.4'
          extension: 'exe'
          classifier: 'linux-x86_64'

      - name: Setup QuickBuf
        run: chmod +x ${{ steps.download-quickbuf.outputs.file }}

      - name: Download WPILib NanoPB
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        id: download-nanopb
        with:
          depth: 1
          branch: 'main'
          owner: 'wpilibsuite'
          repository: 'allwpilib'

      - name: Setup NanoPB
        run: chmod +x allwpilib/wpiutil/src/main/native/thirdparty/nanopb/generator/nanopb_generator
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.x'
      
      - name: Install gRPC tools
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            grpcio-tools

      - name: Generate C++ protobufs
        run: |
          python ./allwpilib/wpiutil/src/main/native/thirdparty/nanopb/generator/nanopb_generator.py \
            -I "protos/" \
            -D "questnav-lib/src/main/native/cpp/gg/questnav/questnav/protos/generated/" \
            -S.cpp \
            -e.npb \
            protos/*.proto


      - name: Move C++ header files
        run: mv questnav-lib/src/main/native/cpp/gg/questnav/questnav/protos/generated/*.npb.h questnav-lib/src/main/native/include/gg/questnav/questnav/protos/generated/

      - name: Generate C# protobuf
        run: protoc -I="protos" --csharp_out=unity/Assets/QuestNav/Protos/Generated protos/*.proto

      - name: Generate Java QuickBuffers
        run: |
          protoc \
            -I="protos" \
            --plugin=protoc-gen-quickbuf=${{ steps.download-quickbuf.outputs.file }} \
            --quickbuf_out=gen_descriptors=true,indent=4:questnav-lib/src/main/java/ \
            protos/*.proto

      - name: Commit all generated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'ci: Generated Protocol Buffers'
          file_pattern: 'unity/Assets/QuestNav/Protos/Generated/*.cs
            questnav-lib/src/main/native/include/gg/questnav/questnav/protos/generated/*.npb.h
            questnav-lib/src/main/native/cpp/gg/questnav/questnav/protos/generated/*.npb.cpp
            questnav-lib/src/main/java/gg/questnav/questnav/protos/generated/*.java'