name: Publish Release
on:
  workflow_dispatch:
    inputs:
      versionYear:
        description: 'Current FRC Year'
        required: true
        default: 2025
        type: number
      wpilibVersion:
        description: 'WPILib version to compile for'
        required: true
        type: string
        default: '2025.3.2'
      versionMajor:
        description: 'Major version'
        required: true
        default: 1
        type: number
      versionMinor:
        description: 'Minor version'
        required: true
        default: 0
        type: number
      versionPatch:
        description: 'Patch version'
        required: true
        default: 0
        type: number
      versionType:
        description: 'Type of version'
        required: true
        type: choice
        options:
          - dev
          - beta
          - rc
          - release
        default: 'dev'
jobs:
  apk:
    uses: QuestNav/QuestNav/.github/workflows/build-questnav-apk.yml@Native
    with:
      versionMajor: ${{ inputs.versionMajor }}
      versionMinor: ${{ inputs.versionMinor }}
      versionPatch: ${{ inputs.versionPatch }}
      versionYear: ${{ inputs.versionYear }}
      versionType: ${{ inputs.versionType }}
    secrets:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  lib:
    uses: QuestNav/QuestNav/.github/workflows/build-questnav-lib.yml@Native
    with:
      versionMajor: ${{ inputs.versionMajor }}
      versionMinor: ${{ inputs.versionMinor }}
      versionPatch: ${{ inputs.versionPatch }}
      versionYear: ${{ inputs.versionYear }}
      versionType: ${{ inputs.versionType }}
      wpilibVersion: ${{ inputs.wpilibVersion }}
      releaseToMaven: true
  github-release:
    runs-on: ubuntu-latest
    needs:
      - apk
      - lib
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Built files
        uses: actions/download-artifact@v4
        with:
          artifact-ids: '${{ needs.lib.outputs.json-artifact-name }},${{ needs.apk.outputs.apk-artifact-name }}'
          path: 'release'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Calculate Version Tag
        id: version
        run: |
          VERSION="${{ inputs.versionYear }}-${{ inputs.versionMajor }}.${{ inputs.versionMinor }}.${{ inputs.versionPatch }}"
          if [ "${{ inputs.versionType }}" != "release" ]; then
            VERSION="${VERSION}-${{ inputs.versionType }}"
          fi
          echo "tag=v${VERSION}" >> $GITHUB_OUTPUT
          echo "name=${VERSION}" >> $GITHUB_OUTPUT

      - name: Release to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          fail_on_unmatched_files: true
          prerelease: ${{ inputs.versionType != 'release' }}
          tag_name: ${{ steps.version.outputs.tag }}
          files: 'release/*'
          token: ${{ secrets.GITHUB_TOKEN }}