name: Publish Release
on:
  workflow_dispatch:
    inputs:
      versionYear:
        description: 'Current FRC Year'
        required: true
        default: '2025'
        type: string
      wpilibVersion:
        description: 'WPILib version to compile for'
        required: true
        type: string
        default: '2025.3.2'
      unityVersion:
        description: 'Unity Editor version'
        required: false
        type: string
        default: '6000.2.6f2'
      versionMajor:
        description: 'Major version'
        required: true
        default: '1'
        type: string
      versionMinor:
        description: 'Minor version'
        required: true
        default: '0'
        type: string
      versionPatch:
        description: 'Patch version'
        required: true
        default: '0'
        type: string
      versionType:
        description: 'Type of version'
        required: true
        type: choice
        options:
          - dev
          - beta
          - rc
          - release
        default: 'dev'
jobs:
  apk:
    uses: QuestNav/QuestNav/.github/workflows/build-questnav-apk.yml@main
    with:
      unityVersion: ${{ inputs.unityVersion }}
      versionMajor: ${{ inputs.versionMajor }}
      versionMinor: ${{ inputs.versionMinor }}
      versionPatch: ${{ inputs.versionPatch }}
      versionYear: ${{ inputs.versionYear }}
      versionType: ${{ inputs.versionType }}
    secrets:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  lib:
    uses: QuestNav/QuestNav/.github/workflows/build-questnav-lib.yml@main
    with:
      versionMajor: ${{ inputs.versionMajor }}
      versionMinor: ${{ inputs.versionMinor }}
      versionPatch: ${{ inputs.versionPatch }}
      versionYear: ${{ inputs.versionYear }}
      versionType: ${{ inputs.versionType }}
      wpilibVersion: ${{ inputs.wpilibVersion }}
      releaseToMaven: true
    secrets:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
  github-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - apk
      - lib
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Built files
        uses: actions/download-artifact@v4
        with:
          artifact-ids: '${{ needs.lib.outputs.json-artifact-name }},${{ needs.apk.outputs.apk-artifact-name }}'
          path: 'release'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Unzip artifacts
        run: |
          for file in release/*; do
          if [[ $file == *.zip ]]; then
           unzip -o "$file" -d release/
           rm "$file"
          fi
          done
          ls -l release/

      - name: Calculate Version Tag
        id: version
        run: |
          VERSION="${{ inputs.versionYear }}-${{ inputs.versionMajor }}.${{ inputs.versionMinor }}.${{ inputs.versionPatch }}"
          if [ "${{ inputs.versionType }}" != "release" ]; then
            VERSION="${VERSION}-${{ inputs.versionType }}"
          fi
          echo "tag=v${VERSION}" >> $GITHUB_OUTPUT
          echo "name=${VERSION}" >> $GITHUB_OUTPUT

      - name: Release to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          fail_on_unmatched_files: true
          prerelease: ${{ inputs.versionType != 'release' }}
          tag_name: ${{ steps.version.outputs.tag }}
          files: release/**
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}